spring.application.name=GX Sneaker

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=GX_SNEAKER2;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=luanchamhoc261@gmail.com
spring.mail.password=totb yqmb yqvh vijs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

file.upload-dir=E:/DATN/DATN/GX Sneaker/uploads/avatars

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB